-- MySQL Script generated by MySQL Workbench
-- Fri Jul 16 13:31:43 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema habi_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `habi_db` ;

-- -----------------------------------------------------
-- Schema habi_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `habi_db` DEFAULT CHARACTER SET latin1 ;
USE `habi_db` ;

-- -----------------------------------------------------
-- Table `habi_db`.`status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `habi_db`.`status` ;

CREATE TABLE IF NOT EXISTS `habi_db`.`status` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(32) NOT NULL,
  `label` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `status_historial_name_uindex` (`name` ASC) VISIBLE,
  UNIQUE INDEX `status_historial_id_uindex` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `habi_db`.`country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `habi_db`.`country` ;

CREATE TABLE IF NOT EXISTS `habi_db`.`country` (
  `id` INT NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `abbreviation` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `habi_db`.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `habi_db`.`city` ;

CREATE TABLE IF NOT EXISTS `habi_db`.`city` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `country_id` INT NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_city_country1_idx` (`country_id` ASC) VISIBLE,
  CONSTRAINT `fk_city_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `habi_db`.`country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `habi_db`.`property`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `habi_db`.`property` ;

CREATE TABLE IF NOT EXISTS `habi_db`.`property` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `status_id` INT(11) NOT NULL,
  `city_id` INT NOT NULL,
  `address` VARCHAR(120) NOT NULL,
  `price` BIGINT(20) NOT NULL,
  `description` TEXT NOT NULL,
  `year` INT(4) NOT NULL,
  `like_count` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `property_id_uindex` (`id` ASC) VISIBLE,
  INDEX `fk_property_status1_idx` (`status_id` ASC) VISIBLE,
  INDEX `fk_property_city1_idx` (`city_id` ASC) VISIBLE,
  CONSTRAINT `fk_property_status1`
    FOREIGN KEY (`status_id`)
    REFERENCES `habi_db`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_property_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `habi_db`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `habi_db`.`status_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `habi_db`.`status_history` ;

CREATE TABLE IF NOT EXISTS `habi_db`.`status_history` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `property_id` INT(11) NOT NULL,
  `status_id` INT(11) NOT NULL,
  `update_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `status_historial_id_uindex` (`id` ASC) VISIBLE,
  INDEX `status_historial_property_id_fk` (`property_id` ASC) VISIBLE,
  INDEX `status_historial_status_id_fk` (`status_id` ASC) VISIBLE,
  CONSTRAINT `status_historial_property_id_fk`
    FOREIGN KEY (`property_id`)
    REFERENCES `habi_db`.`property` (`id`),
  CONSTRAINT `status_historial_status_id_fk`
    FOREIGN KEY (`status_id`)
    REFERENCES `habi_db`.`status` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `habi_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `habi_db`.`user` ;

CREATE TABLE IF NOT EXISTS `habi_db`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `habi_db`.`like_user_property`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `habi_db`.`like_user_property` ;

CREATE TABLE IF NOT EXISTS `habi_db`.`like_user_property` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `property_id` INT(11) NOT NULL,
  `status` SMALLINT NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_like_property1_idx` (`property_id` ASC) VISIBLE,
  INDEX `fk_like_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_like_property1`
    FOREIGN KEY (`property_id`)
    REFERENCES `habi_db`.`property` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_like_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `habi_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
